name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    permissions:
      id-token: write
      contents: read

    name: Build image
    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::999855308786:role/gh-actions-role
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t 999855308786.dkr.ecr.sa-east-1.amazonaws.com/simplebank:${{ github.sha }} .
        docker push 999855308786.dkr.ecr.sa-east-1.amazonaws.com/simplebank:${{ github.sha }}